language: java
services:
- postgresql
before_script:
- psql -c 'create database wimp;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: ZVW8UJP6kOYoLmK3N3LaJ9eL11ARXdDgqKzhmW+lTKLc08NO/A9wh8PqAJQ97ri5BSEzOMblNWFyIpq5YItWbAD9y+6me2iSidQ+YRW2TKabeR1Jr90VwAl24rTYYIw0OfSCkEcg3dYrP2xD2iSf7ujQ6EHYzjgdhIWRHStMEJo0pZmFobukf1fN3A7ffJks9+0JUbR5SmZRhgQguG6SQRdBw4fSbGsP6ZeRJ2cJwzW2zus1jq4cAVWmUHhyaLtBa/ovG8gfhtFHqjR2BIhRgl5jaaarEGfdwiTcCciWvDF8KW4UMIl7tcZLZISOGMaeR14+8WBfAM09ny6BKI//79AJEh/Q7rUeQ5deJpqnuWsSpUTgQlcNTmezBHQgL8mfdm/d9DTB27pgMkZml4iTEtbqMuaDHvUPsy6ZP83KH1RbEsmsUxOikIh4S01NPYPYK3OPLPXCDOSsI/24lDG4fC0c7KkGWOhxJ5PBPf3OHJg55HX/zLkeWCebhKfDsb/wbYENqEguwa2bjuePIj178FYgvuCu4nYbRRsmRJLYGBhDXCI7RNlciF007tIMLyR0emyQnQF/wmkhsJ7ytrKXZfZTKwyVyNTubvQe/iafHUpnEnN07okNgPtZS9TO/vRf43e/1Urk1tVtEvDyCIiWXkZ4zKl/TpIGZmb+6U/Xp4w=
  app: wimp-app-jon-g4c-indy-nov
  on:
    repo: jograca/wimp
